### ISSUE TITLE
yarn安装报错

### ISSUE THREAD

**Issue by kyxiao** [xpioneer/react-typescript#1]
error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by wanwan00** [comment]
How do you solve it？

**Comment by xpioneer** [comment]
可能是yarn的源不稳定，可以配置淘宝的镜像。

**Comment by wanwan00** [comment]
谢谢~





------------------ 原始邮件 ------------------
发件人: "beginner"<notifications@github.com>;
发送时间: 2019年9月22日(星期天) 下午3:00
收件人: "xpioneer/react-typescript"<react-typescript@noreply.github.com>;
抄送: "873830150"<873830150@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [xpioneer/react-typescript] yarn安装报错 (#1)




可能是yarn的源不稳定，可以配置淘宝的镜像。
